
spring.application.name=studentmanagement

# MySQL connection (Uses Render variables if they exist, else uses your local setup)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/studentApplicationApp}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:system}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Tells Render which port to use
server.port=${PORT:8081}